[package]
name = "net_helper"
version = "0.1.0"
edition = "2024"
keywords = ['networking', 'zero-copy', 'netmap', 'low-latency', 'ffi']
build = "build.rs"

[package.metadata.docs.rs]
features = ["disable-netmap-kernel"]

[dependencies]
bitflags = "2.6" # Updated to latest version
tokio = { version = "1.40", features = [
    "net",
    "io-util",
    "macros",
    "rt",
], optional = true } # Updated version
core_affinity = { version = "0.8", optional = true }
crossbeam = { version = "0.8", optional = true }
libc = "0.2"
reed-solomon-erasure = { version = "6.0.0", optional = true }
thiserror = "2.0" # Updated to latest version
zero-packet = "0.1.0"


[build-dependencies]
bindgen = "0.72.1"
cc = "1.0"

[features]
disable-netmap-kernel = []
sys = []
netmap_with_libs = []
